//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int id { get; set; }
        public int idTournament { get; set; }
        public int idTeamOne { get; set; }
        public int pointsTeamOne { get; set; }
        public int idTeamTwo { get; set; }
        public int pointsTeamTwo { get; set; }
        public Nullable<System.DateTime> dateTimeStart { get; set; }
        public string matchStage { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
