//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamComposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamComposition()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int id { get; set; }
        public int idPlayerOne { get; set; }
        public int idPlayerTwo { get; set; }
        public int idPlayerThree { get; set; }
        public int idPlayerFour { get; set; }
        public int idPlayerFive { get; set; }
        public Nullable<int> idCoach { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        public virtual Player Player3 { get; set; }
        public virtual Player Player4 { get; set; }
        public virtual Player Player5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
